[pytest]
python_files = *_tests.py test_*.py
python_classes = Test*
python_functions = test_*

# Регистрируем кастомные маркировки
markers =
    main: Маркировка для главных тестов
    positive: Маркировка для позитивных тестов
    negative: Маркировка для негативных тестов